/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login/route'
import { Route as ContentsRouteImport } from './routes/_contents/route'
import { Route as IndexImport } from './routes/index'
import { Route as ContentsUsersRouteImport } from './routes/_contents/users/route'
import { Route as ContentsSettingsRouteImport } from './routes/_contents/settings/route'
import { Route as ContentsCCCCRouteImport } from './routes/_contents/CCCC/route'
import { Route as ContentsBBBBRouteImport } from './routes/_contents/BBBB/route'
import { Route as ContentsAAAARouteImport } from './routes/_contents/AAAA/route'

// Create/Update Routes

const LoginRouteRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ContentsRouteRoute = ContentsRouteImport.update({
  id: '/_contents',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContentsUsersRouteRoute = ContentsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ContentsRouteRoute,
} as any)

const ContentsSettingsRouteRoute = ContentsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ContentsRouteRoute,
} as any)

const ContentsCCCCRouteRoute = ContentsCCCCRouteImport.update({
  id: '/CCCC',
  path: '/CCCC',
  getParentRoute: () => ContentsRouteRoute,
} as any)

const ContentsBBBBRouteRoute = ContentsBBBBRouteImport.update({
  id: '/BBBB',
  path: '/BBBB',
  getParentRoute: () => ContentsRouteRoute,
} as any)

const ContentsAAAARouteRoute = ContentsAAAARouteImport.update({
  id: '/AAAA',
  path: '/AAAA',
  getParentRoute: () => ContentsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_contents': {
      id: '/_contents'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ContentsRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/_contents/AAAA': {
      id: '/_contents/AAAA'
      path: '/AAAA'
      fullPath: '/AAAA'
      preLoaderRoute: typeof ContentsAAAARouteImport
      parentRoute: typeof ContentsRouteImport
    }
    '/_contents/BBBB': {
      id: '/_contents/BBBB'
      path: '/BBBB'
      fullPath: '/BBBB'
      preLoaderRoute: typeof ContentsBBBBRouteImport
      parentRoute: typeof ContentsRouteImport
    }
    '/_contents/CCCC': {
      id: '/_contents/CCCC'
      path: '/CCCC'
      fullPath: '/CCCC'
      preLoaderRoute: typeof ContentsCCCCRouteImport
      parentRoute: typeof ContentsRouteImport
    }
    '/_contents/settings': {
      id: '/_contents/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ContentsSettingsRouteImport
      parentRoute: typeof ContentsRouteImport
    }
    '/_contents/users': {
      id: '/_contents/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ContentsUsersRouteImport
      parentRoute: typeof ContentsRouteImport
    }
  }
}

// Create and export the route tree

interface ContentsRouteRouteChildren {
  ContentsAAAARouteRoute: typeof ContentsAAAARouteRoute
  ContentsBBBBRouteRoute: typeof ContentsBBBBRouteRoute
  ContentsCCCCRouteRoute: typeof ContentsCCCCRouteRoute
  ContentsSettingsRouteRoute: typeof ContentsSettingsRouteRoute
  ContentsUsersRouteRoute: typeof ContentsUsersRouteRoute
}

const ContentsRouteRouteChildren: ContentsRouteRouteChildren = {
  ContentsAAAARouteRoute: ContentsAAAARouteRoute,
  ContentsBBBBRouteRoute: ContentsBBBBRouteRoute,
  ContentsCCCCRouteRoute: ContentsCCCCRouteRoute,
  ContentsSettingsRouteRoute: ContentsSettingsRouteRoute,
  ContentsUsersRouteRoute: ContentsUsersRouteRoute,
}

const ContentsRouteRouteWithChildren = ContentsRouteRoute._addFileChildren(
  ContentsRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ContentsRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/AAAA': typeof ContentsAAAARouteRoute
  '/BBBB': typeof ContentsBBBBRouteRoute
  '/CCCC': typeof ContentsCCCCRouteRoute
  '/settings': typeof ContentsSettingsRouteRoute
  '/users': typeof ContentsUsersRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ContentsRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/AAAA': typeof ContentsAAAARouteRoute
  '/BBBB': typeof ContentsBBBBRouteRoute
  '/CCCC': typeof ContentsCCCCRouteRoute
  '/settings': typeof ContentsSettingsRouteRoute
  '/users': typeof ContentsUsersRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_contents': typeof ContentsRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/_contents/AAAA': typeof ContentsAAAARouteRoute
  '/_contents/BBBB': typeof ContentsBBBBRouteRoute
  '/_contents/CCCC': typeof ContentsCCCCRouteRoute
  '/_contents/settings': typeof ContentsSettingsRouteRoute
  '/_contents/users': typeof ContentsUsersRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/AAAA'
    | '/BBBB'
    | '/CCCC'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/AAAA' | '/BBBB' | '/CCCC' | '/settings' | '/users'
  id:
    | '__root__'
    | '/'
    | '/_contents'
    | '/login'
    | '/_contents/AAAA'
    | '/_contents/BBBB'
    | '/_contents/CCCC'
    | '/_contents/settings'
    | '/_contents/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentsRouteRoute: typeof ContentsRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentsRouteRoute: ContentsRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_contents",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_contents": {
      "filePath": "_contents/route.tsx",
      "children": [
        "/_contents/AAAA",
        "/_contents/BBBB",
        "/_contents/CCCC",
        "/_contents/settings",
        "/_contents/users"
      ]
    },
    "/login": {
      "filePath": "login/route.tsx"
    },
    "/_contents/AAAA": {
      "filePath": "_contents/AAAA/route.tsx",
      "parent": "/_contents"
    },
    "/_contents/BBBB": {
      "filePath": "_contents/BBBB/route.tsx",
      "parent": "/_contents"
    },
    "/_contents/CCCC": {
      "filePath": "_contents/CCCC/route.tsx",
      "parent": "/_contents"
    },
    "/_contents/settings": {
      "filePath": "_contents/settings/route.tsx",
      "parent": "/_contents"
    },
    "/_contents/users": {
      "filePath": "_contents/users/route.tsx",
      "parent": "/_contents"
    }
  }
}
ROUTE_MANIFEST_END */
