/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */
import type { InvalidParam } from "./invalidParam";

/**
 * 不正リクエスト
 */
export interface BadRequestError {
  detail?: string;
  "invalid-params"?: InvalidParam[];
  /** エラータイトル */
  title?: string;
}
