/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

/**
 * 409
 */
export interface ConflictError {
  /** エラーの詳細 */
  detail: string;
  title: string;
}
