/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

/**
 * 不正リクエストについての詳細
 */
export interface InvalidParam {
  /** エラーが発生したフィールド名 */
  name: string;
  /** エラーの理由 */
  reason: string;
}
