/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

/**
 * ログイン時のユーザー情報
 */
export interface LoginUserForm {
  /**
   * ログインEmail
   * @minLength 1
   * @maxLength 100
   */
  email: string;
  /**
   * パスワード
   * @minLength 1
   * @maxLength 100
   */
  password: string;
}
