/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

/**
 * ログイン時のユーザー情報
 */
export interface LoginUserForm {
  /** ログインEmail */
  email: string;
  /** パスワード */
  password: string;
}
