/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */
import type { MeetingResponseDTO } from "./meetingResponseDTO";

/**
 * ミーティングのリスト
 */
export interface MeetingResponseDTOList {
  results: MeetingResponseDTO[];
}
