/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

/**
 * ミーティング登録用
 */
export interface MeetingSearchForm {
  /** 検索終了 */
  searchEndDate?: string;
  /** 開催者IDList */
  searchOpenerId?: number[];
  /** 検索開始 */
  searchStartDate?: string;
  /**
   * 検索文字
   * @minLength 1
   * @maxLength 100
   */
  searchWord?: string;
}
