/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

/**
 * ミーティング登録用
 */
export interface MeetingForm {
  /**
   * 詳細情報
   * @minLength 1
   * @maxLength 500
   */
  detail: string;
  /**
   * 終了時間
   * @maxLength 5
   */
  endTime: string;
  /** 開催日 */
  eventDate: string;
  /** 開催者ID */
  openerId: number;
  /**
   * 開始時間
   * @maxLength 5
   */
  startTime: string;
  /**
   * ミーティング名
   * @minLength 1
   * @maxLength 100
   */
  title: string;
}
