/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

/**
 * メーティングの結果情報
 */
export interface MeetingResponseDTO {
  /** ID */
  id: number;
  /** title */
  title: string;
}
