/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

/**
 * ミーティングの結果情報
 */
export interface MeetingResponseDTO {
  /** detail */
  detail: string;
  /** 終了時間 */
  endTime: string;
  /** 開催日 */
  eventDate: string;
  /** ID */
  id: number;
  /** 開催者ID */
  openerId: number;
  /** 開始時間 */
  startTime: string;
  /** title */
  title: string;
}
