/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

export interface OrderProp {
  /** ソートする順序 */
  direction?: string;
  /** ソートするフィールド名 */
  property?: string;
}
