/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

export interface Pagination {
  /**
   * max count that can be rerieved from DB at once, same as item count per page
   * @minimum 0
   */
  limit?: number;
  /**
   * starting position to fetch, same as first item index in the page
   * @minimum 0
   */
  offset?: number;
  /**
   * total count of search results in DB
   * @minimum 0
   */
  total?: number;
}
