/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

/**
 * 指定したリソースは存在しない
 */
export interface ResourceNotFoundError {
  /** エラーの詳細 */
  detail: string;
  /** エラーのタイプ */
  title: string;
}
