/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * PRODUCT API DOC
 * PRODUCT API DOC
 * OpenAPI spec version: 0.0.1
 */

/**
 * ログイン時の結果情報
 */
export interface UserResponseDTO {
  /**
   * ログインEmail
   * @minLength 1
   * @maxLength 100
   */
  email: string;
  /** ROLE */
  role: string;
}
